<?php

namespace App\Http\Requests\DisHes;

use App\Http\Requests\ValidateMessage;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Request;

class DishesRequest extends FormRequest
{
    use ValidateMessage;
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $countSelectDishes = sizeof($this->input('select_dishes', []));
        if ($this->method() == "POST") {
            return [
                'select_meal' => 'required|string|max:255',
                'number_people' => 'required|integer',
                'select_restaurant' => 'required|string|max:255',
                'select_dishes' => 'required|array',
                'number_dishes' => 'required|array|size:'.$countSelectDishes,
            ];
        }
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
